global:
  ENVIRONMENT: "Staging"

common:
  namespace: kube2py-staging

mysql:
  namespace: mysql-staging

kube2py:
  configs:
    APP_ENV: "testing-helm-staging"

  secrets:
    password: placeholder
    login: placeholder

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "100m"

  hpa:
    enabled: true
    minReplicas: 3
    maxReplicas: 5
